### PR TITLE
Content

### PR DESCRIPTION
**Pull request by aliceminotto**

### CODE REVIEW

**Comment by aliceminotto** [comment]
with jekyll everything is fine, with the github preview page the carousel acts very weird, and there is no tag cloud (this is not a big deal i think)

**Comment by danmaclean** [comment]
Nice job Alice! Can you take a quick look at tsl-training.github.io and note where there are pictures missing. Looks like some didn't get added to the Repo!

**Comment by aliceminotto** [comment]
Hi Dan, I looked at it, but there thee are all the images i added (I didn't add the command line that was in the main page in the previous website as now there is the carousel, and I didn't add your picture in about.html cause I wasn't sure you wanted it or if you wanted the same picture, where you talking about these?).
Alice

Date: Thu, 18 Feb 2016 14:08:43 -0800

**Comment by danmaclean** [comment]
OK, this is fine. Can you remove the contact us email form thing, Im not sure that it works! I don't think we really want a form that works on an external service there anyway - instead can you look at adding contact details by providing a link to the TSL sites and adding in a gif of the bioinformatics@tsl.ac.uk address.

Thanks!

**Comment by aliceminotto** [comment]
Sure! But what do you mean by a gif of the address?

Date: Wed, 24 Feb 2016 06:47:44 -0800

**Comment by danmaclean** [comment]
insert a picture of the words bioinformatics@tsl.ac.uk

**Pull request merged**
